name: Update GMA 7 M3U8 Live Stream Link

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:     # Manual trigger

jobs:
  update-m3u8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install yt-dlp and other tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg  # optional but helpful
          python -m pip install --upgrade pip
          pip install yt-dlp requests

      - name: Debug IP and Headers (Optional)
        run: |
          curl ifconfig.me
          curl -I https://www.youtube.com

      - name: Run Script
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
        run: python update_script.py
