name: Update GMA 7 M3U8 Live Stream Link

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:     # Manual trigger (optional)

jobs:
  update-m3u8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install yt-dlp

      - name: Run Script
        env:
          MY_PAT: ${{ secrets.MY_PAT }}
        run: python update_script.py
