name: Update M3U8 Live Stream Link

on:
  schedule:
    # Tumatakbo kada oras, sa ika-20 minuto ng oras
    - cron: '20 * * * *'
  workflow_dispatch:

jobs:
  update-link:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # yt-dlp at requests na lang ang kailangan
          pip install yt-dlp requests

      - name: Run the M3U8 update script
        env:
          # GITHUB_TOKEN na lang ang kailangan mula sa secrets!
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
          PLAYLIST_PATH: 'ph.m3u'
        run: python update_script.py
