name: Update M3U8 Live Stream Link

on:
  schedule:
    # Tumatakbo kada oras, sa ika-20 minuto ng oras (e.g., 1:20, 2:20, atbp.)
    # Pwede mong palitan ang '20' sa ibang numero mula 0-59.
    - cron: '20 * * * *'
    
  # Pinapayagan kang patakbuhin ito nang manu-mano mula sa "Actions" tab ng GitHub
  workflow_dispatch:

jobs:
  update-link:
    # Gagamit ng isang virtual machine na may Ubuntu Linux
    runs-on: ubuntu-latest

    steps:
      # Step 1: Kinukuha ang kopya ng iyong repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Inihahanda ang Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Ini-install ang mga kailangan ng script
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # yt-dlp at requests na lang ang kailangan
          pip install yt-dlp requests

      # Step 4: Pinapatakbo ang iyong Python script
      - name: Run the M3U8 update script
        env:
          # Kinukuha ang mga "secrets" at iba pang impormasyon
          # para ipasa sa iyong Python script.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
          PLAYLIST_PATH: 'ph.m3u' # Palitan mo ito kung iba ang pangalan ng iyong playlist file
        run: python update_script.py
